# fly.toml app configuration file generated for twilio-replay on 2025-07-08T18:21:56Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'twilio-replay'
primary_region = 'iad'

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[[mounts]]
  source = 'recordings_data'
  destination = '/public/recordings'

[http_service]
  internal_port = 3000
  force_https = true

[[services]]
  protocol = 'tcp'
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '1gb'
  cpu_kind = 'performance'
  cpus = 1
